spring.application.name=Life_ledger_backend

# Spring Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/life_ledger
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Server Configuration
server.port=9090

# JWT / Security Config
jwt.secret=YourJWTSecretKeyHereChangeThisToASecureRandomString123456789
jwt.expirationMs=86400000

# Logging
logging.level.org.springframework=INFO
logging.level.com.lifeledger=DEBUG

# redis
spring.data.redis.repositories.enabled=false

# File Upload Properties
file.upload-dir=uploads/

# Cloudnary setup
cloudinary.cloud_name= dmknqklhp
cloudinary.api_key= 899131321422671
cloudinary.api_secret= PRw_qvwRHLjwcq2MHXEXgItBMiI


# openapi key
openai.api.key=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

# gemin api key
gemini.api.key= AIzaSyBbihA9ZRQb0bHch_kXHDa50VXc8f_zI6M
